# Generated by Django 5.0.6 on 2024-05-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=57)),
                ('country', models.CharField(max_length=57)),
                ('city', models.CharField(max_length=57)),
                ('date_founded', models.DateField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('History', 'History'), ('Drama', 'Drama'), ('Classic', 'Classic'), ('Biography', 'Biography'), ('Thriller', 'Thriller'), ('Romance', 'Romance')], max_length=20)),
                ('material', models.CharField(choices=[('WEAK', 'WEAK'), ('STRONG', 'STRONG')], max_length=10)),
                ('title', models.CharField(max_length=57)),
                ('image', models.ImageField(blank=True, null=True, upload_to='admin/')),
                ('isbn', models.CharField(max_length=57)),
                ('year_published', models.IntegerField()),
                ('num_pages', models.IntegerField()),
                ('dimensions', models.CharField(max_length=57)),
                ('price', models.IntegerField()),
                ('house_publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kol.housepublish')),
            ],
        ),
    ]
